name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Release
    uses: ./.github/workflows/build-reusable.yml
    with:
      bump_version: true
      version: ${{ github.ref_name }}

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4 # Updated action version
        with:
          name: ox_lib_build # Updated artifact name

      # This dependency is archived, possibly replace it with a maintained one
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: ${{ github.ref_name }}
          prerelease: false
          files: ox_lib.zip
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
